
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Nov 27 14:04:44 EST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRLIT = 5;
  public static final int rw_WHILE = 14;
  public static final int rw_BOOL = 38;
  public static final int LBRACKET = 8;
  public static final int rw_IF = 39;
  public static final int SLASH = 26;
  public static final int rw_CONTINUE = 42;
  public static final int rw_FALSE = 25;
  public static final int LPAREN = 22;
  public static final int SEMI = 9;
  public static final int rw_PRINT = 28;
  public static final int rw_TRUE = 35;
  public static final int rw_VAR = 48;
  public static final int MINUS = 16;
  public static final int RPAREN = 23;
  public static final int NOT = 40;
  public static final int rw_VOID = 44;
  public static final int INTLIT = 3;
  public static final int LT = 13;
  public static final int rw_CONST = 12;
  public static final int COMMA = 20;
  public static final int rw_ELSE = 27;
  public static final int GEQ = 24;
  public static final int rw_FUNC = 46;
  public static final int PLUS = 29;
  public static final int rw_READ = 18;
  public static final int rw_INT = 21;
  public static final int EOF = 0;
  public static final int rw_FOR = 45;
  public static final int RBRACKET = 36;
  public static final int error = 1;
  public static final int DASH = 49;
  public static final int rw_PACKAGE = 47;
  public static final int COR = 6;
  public static final int rw_CLASS = 7;
  public static final int EQ = 37;
  public static final int rw_RETURN = 17;
  public static final int ASG = 34;
  public static final int TIMES = 19;
  public static final int CHARLIT = 4;
  public static final int COLON = 43;
  public static final int LBRACE = 30;
  public static final int rw_CHAR = 15;
  public static final int RBRACE = 31;
  public static final int CAND = 11;
  public static final int LEQ = 32;
  public static final int rw_BREAK = 41;
  public static final int GT = 10;
  public static final int NOTEQ = 33;
  public static final int IDENTIFIER = 2;
}

